import {
  Product,
  Category,
  DigitalInventoryItem,
  Order,
  Subscription,
  Coupon,
  Review,
  Ticket,
  AuditLog,
  BlogPost,
  CMSPage,
  StoreSettings,
  User,
  NotificationItem,
} from '../src/types';

export const initialCategories: Category[] = [
  {
    id: 'cat-projectors',
    name: 'Smart Projectors',
    slug: 'projectors',
    icon: 'Tv',
    description: 'Magcubic, HCS, Amlogic & Smartberry 4K/1080P Smart Projectors with 10% direct margin pricing.',
    isFeatured: true,
    productCount: 8,
  },
  {
    id: 'cat-games',
    name: 'Games',
    slug: 'games',
    icon: 'Gamepad2',
    description: 'Steam keys, Epic codes, in-game currency, season passes & console activations.',
    isFeatured: true,
    productCount: 16,
  },
  {
    id: 'cat-software',
    name: 'Software',
    slug: 'software',
    icon: 'Laptop',
    description: 'Windows 11, Office 2024, JetBrains IDEs, Adobe CC & VPN security suites.',
    isFeatured: true,
    productCount: 18,
  },
  {
    id: 'cat-ai-tools',
    name: 'AI Tools',
    slug: 'ai-tools',
    icon: 'Cpu',
    description: 'ChatGPT Plus, Claude 3.5 Sonnet, Midjourney, Cursor Pro, Runway & ElevenLabs.',
    isFeatured: true,
    productCount: 14,
  },
  {
    id: 'cat-subscriptions',
    name: 'Subscriptions',
    slug: 'subscriptions',
    icon: 'Tv',
    description: 'Netflix 4K, Spotify Premium, YouTube Premium, Xbox Game Pass & PS Plus.',
    isFeatured: true,
    productCount: 12,
  },
  {
    id: 'cat-giftcards',
    name: 'Gift Cards',
    slug: 'gift-cards',
    icon: 'Gift',
    description: 'Steam Wallet, Apple, Amazon, Google Play & PlayStation Network vouchers.',
    isFeatured: true,
    productCount: 10,
  },
  {
    id: 'cat-bundles',
    name: 'Bundles',
    slug: 'bundles',
    icon: 'Sparkles',
    description: 'AI Creator Super-Bundle, Streaming Masterpass, and Developer Power-Packs.',
    isFeatured: true,
    productCount: 6,
  },
  {
    id: 'cat-free-tools',
    name: 'Free Tools',
    slug: 'free-tools',
    icon: 'Zap',
    description: 'Free open-source LLM runners, 256-bit key vault generators & SEO utilities.',
    isFeatured: true,
    productCount: 5,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-kaspersky-total-sec',
    name: 'Kaspersky Total Security',
    slug: 'kaspersky-total-security',
    sku: 'SEC-KASP-5D',
    productType: 'software_license',
    brand: 'Kaspersky',
    category: 'software',
    description: 'Kaspersky Total Security complete protection. 5 devices · antivirus + VPN + parental controls · multi-platform security for Windows, macOS, Android, and iOS.',
    shortDescription: '5 devices · antivirus + VPN + parental.',
    images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 4.00,
    salePrice: 4.00,
    pricePKR: 1116,
    currency: 'USD',
    stock: 45,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'Kaspersky', 'Antivirus', 'VPN', 'Security'],
    isFeatured: true,
    isPopular: true,
    rating: 4.9,
    reviewsCount: 120,
    createdAt: '2025-02-16T08:00:00Z',
  },
  {
    id: 'prod-spotify-prem-3m',
    name: 'Spotify Premium 3 Month',
    slug: 'spotify-premium-3-month',
    sku: 'SUB-SPOT-3M',
    productType: 'streaming_service',
    brand: 'Spotify',
    category: 'subscriptions',
    description: 'Spotify Premium 3 Months Individual Plan. 3 months · ad-free · offline downloads · 320kbps high-fidelity music streaming on any device.',
    shortDescription: '3 months · ad-free · offline downloads.',
    images: [
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2.80,
    salePrice: 2.80,
    pricePKR: 781,
    currency: 'USD',
    stock: 60,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '3_months',
    tags: ['Subscription', 'Spotify', 'Music', 'Streaming'],
    isFeatured: true,
    isPopular: true,
    rating: 4.95,
    reviewsCount: 240,
    createdAt: '2025-02-16T08:15:00Z',
  },
  {
    id: 'prod-jasper-ai-tool',
    name: 'Jasper AI',
    slug: 'jasper-ai',
    sku: 'AI-JASPER-1M',
    productType: 'saas',
    brand: 'Jasper',
    category: 'ai-tools',
    description: 'Jasper AI Content Marketing Platform. AI writing for marketing — 10x faster. Generate high-converting copy, blog posts, social media campaigns, and brand voice automation.',
    shortDescription: 'AI writing for marketing — 10x faster.',
    images: [
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 12.00,
    salePrice: 12.00,
    pricePKR: 3348,
    currency: 'USD',
    stock: 25,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['AI Tools', 'Jasper AI', 'AI Pick', 'Featured', 'Writing'],
    isFeatured: true,
    isPopular: true,
    isTrending: true,
    rating: 4.92,
    reviewsCount: 165,
    createdAt: '2025-02-16T08:30:00Z',
  },
  {
    id: 'prod-eset-internet-sec',
    name: 'ESET Internet Security',
    slug: 'eset-internet-security',
    sku: 'SEC-ESET-3D',
    productType: 'software_license',
    brand: 'ESET',
    category: 'software',
    description: 'ESET Internet Security multi-layered malware protection. Award-winning antivirus · 3 devices · 1 year. Includes banking protection, firewall, and anti-phishing.',
    shortDescription: 'Award-winning antivirus · 3 devices · 1 year.',
    images: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2.50,
    salePrice: 2.50,
    pricePKR: 697,
    currency: 'USD',
    stock: 35,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'ESET', 'Antivirus', 'Security'],
    isFeatured: true,
    isPopular: true,
    rating: 4.88,
    reviewsCount: 94,
    createdAt: '2025-02-16T08:45:00Z',
  },
  {
    id: 'prod-norton-360-deluxe',
    name: 'Norton 360 Deluxe',
    slug: 'norton-360-deluxe',
    sku: 'SEC-NORTON-5D',
    productType: 'software_license',
    brand: 'Norton',
    category: 'software',
    description: 'Norton 360 Deluxe all-in-one protection. 5 devices · antivirus + VPN + 50GB backup · Dark Web Monitoring and Password Manager.',
    shortDescription: '5 devices · antivirus + VPN + 50GB backup.',
    images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3.50,
    salePrice: 3.50,
    pricePKR: 977,
    currency: 'USD',
    stock: 40,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'Norton', 'Antivirus', 'VPN', 'Backup'],
    isFeatured: true,
    isPopular: true,
    rating: 4.89,
    reviewsCount: 110,
    createdAt: '2025-02-16T09:00:00Z',
  },
  {
    id: 'prod-mcafee-total-prot',
    name: 'McAfee Total Protection',
    slug: 'mcafee-total-protection',
    sku: 'SEC-MCAFEE-5D',
    productType: 'software_license',
    brand: 'McAfee',
    category: 'software',
    description: 'McAfee Total Protection premium security suite. 5 devices · antivirus + identity + VPN · comprehensive cross-device privacy and web safety.',
    shortDescription: '5 devices · antivirus + identity + VPN.',
    images: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3.00,
    salePrice: 3.00,
    pricePKR: 837,
    currency: 'USD',
    stock: 50,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'McAfee', 'Antivirus', 'Identity', 'VPN'],
    isFeatured: true,
    isPopular: true,
    rating: 4.85,
    reviewsCount: 88,
    createdAt: '2025-02-16T09:15:00Z',
  },
  {
    id: 'prod-nordvpn-playbeat',
    name: 'NordVPN',
    slug: 'nordvpn',
    sku: 'SEC-NORDVPN-1Y',
    productType: 'software_license',
    brand: 'NordVPN',
    category: 'software',
    description: 'NordVPN high-speed private VPN. 5,000+ servers · military encryption · no logs · double VPN encryption and threat protection.',
    shortDescription: '5,000+ servers · military encryption · no logs.',
    images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 4.00,
    salePrice: 4.00,
    pricePKR: 1116,
    currency: 'USD',
    stock: 75,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'NordVPN', 'VPN', 'Privacy', 'Security'],
    isFeatured: true,
    isPopular: true,
    rating: 4.94,
    reviewsCount: 280,
    createdAt: '2025-02-16T09:30:00Z',
  },
  {
    id: 'prod-expressvpn-playbeat',
    name: 'ExpressVPN',
    slug: 'expressvpn',
    sku: 'SEC-EXPRESSVPN-1Y',
    productType: 'software_license',
    brand: 'ExpressVPN',
    category: 'software',
    description: 'ExpressVPN ultra-fast gigabit connection. 3,000+ servers · 94 countries · split tunneling · Lightway protocol and TrustedServer technology.',
    shortDescription: '3,000+ servers · 94 countries · split tunneling.',
    images: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 4.50,
    salePrice: 4.50,
    pricePKR: 1256,
    currency: 'USD',
    stock: 65,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'ExpressVPN', 'VPN', 'Privacy', 'Speed'],
    isFeatured: true,
    isPopular: true,
    rating: 4.96,
    reviewsCount: 310,
    createdAt: '2025-02-16T09:45:00Z',
  },
  {
    id: 'prod-youtube-prem-pb',
    name: 'YouTube Premium',
    slug: 'youtube-premium',
    sku: 'SUB-YT-PREM',
    productType: 'streaming_service',
    brand: 'Google',
    category: 'subscriptions',
    description: 'YouTube Premium uninterrupted streaming. Ad-free · background play · YouTube Music · 4K resolution and offline video downloads.',
    shortDescription: 'Ad-free · background play · YouTube Music.',
    images: [
      'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2.20,
    salePrice: 2.20,
    pricePKR: 614,
    currency: 'USD',
    stock: 55,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Subscription', 'YouTube', 'Streaming', 'Google'],
    isFeatured: true,
    rating: 4.98,
    reviewsCount: 340,
    createdAt: '2025-02-16T09:50:00Z',
  },
  {
    id: 'prod-apple-tv-pb',
    name: 'Apple TV+',
    slug: 'apple-tv-plus',
    sku: 'SUB-ATV-PLUS',
    productType: 'streaming_service',
    brand: 'Apple',
    category: 'subscriptions',
    description: 'Apple TV+ award-winning entertainment. Apple Originals · 4K HDR Dolby Vision · Spatial Audio on iPhone, iPad, Apple TV, smart TVs, and browser.',
    shortDescription: 'Apple Originals · 4K HDR Dolby Vision.',
    images: [
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2.50,
    salePrice: 2.50,
    pricePKR: 698,
    currency: 'USD',
    stock: 30,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Subscription', 'Apple', 'Streaming', 'Apple TV+'],
    isFeatured: true,
    rating: 4.91,
    reviewsCount: 140,
    createdAt: '2025-02-16T09:55:00Z',
  },
  {
    id: 'prod-ms365-family-pb',
    name: 'Microsoft 365 Family',
    slug: 'microsoft-365-family',
    sku: 'SUB-MS365-FAM',
    productType: 'software_license',
    brand: 'Microsoft',
    category: 'software',
    description: 'Microsoft 365 Family productivity suite. 6 users · Office apps · 1TB each · Word, Excel, PowerPoint, Outlook, OneDrive cloud storage, and Microsoft Defender.',
    shortDescription: '6 users · Office apps · 1TB each.',
    images: [
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 10.00,
    salePrice: 10.00,
    pricePKR: 2790,
    currency: 'USD',
    stock: 40,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Software', 'Microsoft 365', 'Office', 'Cloud', 'Family'],
    isFeatured: true,
    rating: 4.97,
    reviewsCount: 215,
    createdAt: '2025-02-16T09:58:00Z',
  },
  {
    id: 'prod-disney-plus-pb',
    name: 'Disney+ Premium 4K',
    slug: 'disney-plus-premium',
    sku: 'SUB-DISNEY-4K',
    productType: 'streaming_service',
    brand: 'Disney',
    category: 'subscriptions',
    description: 'Disney+ Premium 4K Ultra HD entertainment. Marvel · Star Wars · Pixar · 4K Ultra HD · IMAX Enhanced, Dolby Atmos, and 4 simultaneous streams.',
    shortDescription: 'Marvel · Star Wars · Pixar · 4K Ultra HD.',
    images: [
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3.00,
    salePrice: 3.00,
    pricePKR: 837,
    currency: 'USD',
    stock: 50,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Subscription', 'Disney+', 'Streaming', 'Marvel', '4K'],
    isFeatured: true,
    rating: 4.92,
    reviewsCount: 190,
    createdAt: '2025-02-16T10:00:00Z',
  },
  {
    id: 'prod-magcubic-hy300-pro',
    name: 'Magcubic HY300 PRO Smart Portable Projector',
    slug: 'magcubic-hy300-pro',
    sku: 'ZB-HY300-PRO',
    productType: 'custom_product',
    brand: 'Magcubic',
    category: 'projectors',
    description: 'Magcubic HY300 Pro Mini Portable Smart Projector. Powered by Android 14.0 and Allwinner H713 Quad-Core CPU with Mali-G31 GPU. Features Native 720P HD resolution with 4K decoding, 200 ANSI Lumens, and an innovative 180° rotatable gimbal stand for ceiling projection. Equipped with Dual-Band WiFi 6 (2.4G/5G), Bluetooth 5.0, built-in 3W HiFi speaker, and up to 130-inch display projection. Compact 0.4kg ultra-lightweight design with HDMI, USB, and 3.5mm audio ports.',
    shortDescription: 'Native 720P • 4K Decoded • Android 14 • 180° Gimbal Stand • WiFi 6 & BT 5.0 • 200 ANSI',
    images: [
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 88.87,
    salePrice: 88.87,
    costPrice: 80.79,
    pricePKR: 24750,
    costPricePKR: 22500,
    profitPKR: 2250,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hy300-pro',
    currency: 'USD',
    stock: 25,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['Magcubic', 'HY300 Pro', 'Projector', 'Android 14', 'WiFi 6', '4K Support', 'ZeroByte'],
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    rating: 4.9,
    reviewsCount: 86,
    systemRequirements: [
      'Power Input: AC 90-260V / 50-60Hz',
      'Native Resolution: 1280x720P (Supports 4K/8K decoding)',
      'Brightness: 200 ANSI Lumens',
      'OS: Android 14.0 with Google Play & YouTube',
      'Connectivity: Dual-Band WiFi 6 + Bluetooth 5.0',
      'Ports: HDMI 2.0, USB 2.0, 3.5mm Headphone Jack',
    ],
    activationGuide: 'Brand new in box. Package includes Magcubic HY300 PRO Projector, IR Remote Control, Power Cable, and English User Manual with 1-Year Local Warranty.',
    createdAt: '2025-02-16T10:00:00Z',
  },
  {
    id: 'prod-hy300-plus',
    name: 'HY300 Plus Smart Projector',
    slug: 'hy300-plus-projector',
    sku: 'ZB-HY300-PLUS',
    productType: 'custom_product',
    brand: 'Magcubic',
    category: 'projectors',
    description: 'HY300 Plus Smart Portable Cinema Projector. Upgraded optical engine with 260 ANSI Lumens brightness and native 720P HD resolution with 4K video input support. Runs Android smart OS with built-in streaming apps. Features motorized remote electric focusing, 180° flexible swivel projection angle, automatic keystone correction, Dual-Band WiFi 6, and Bluetooth 5.2.',
    shortDescription: '260 ANSI Lumens • Electric Focus • 180° Swivel Projection • Android Smart OS • WiFi 6',
    images: [
      'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 88.87,
    salePrice: 88.87,
    costPrice: 80.79,
    pricePKR: 24750,
    costPricePKR: 22500,
    profitPKR: 2250,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hy300-plus',
    currency: 'USD',
    stock: 20,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HY300 Plus', 'Magcubic', 'Smart Projector', 'Electric Focus', 'WiFi 6', 'ZeroByte'],
    isFeatured: true,
    rating: 4.88,
    reviewsCount: 64,
    systemRequirements: [
      'Native Resolution: 1280x720P HD (4K video input supported)',
      'Brightness: 260 ANSI Lumens',
      'Focus Mode: Motorized Remote Electric Focus',
      'Angle: 180° Swivel Gimbal Bracket',
      'Wireless: Dual-Band WiFi 6 & Bluetooth 5.2',
    ],
    activationGuide: 'Brand new in box with remote control, power adapter, and quick setup guide.',
    createdAt: '2025-02-16T10:15:00Z',
  },
  {
    id: 'prod-magcubic-hy300pro-plus',
    name: 'Magcubic HY300Pro Plus Smart Projector',
    slug: 'magcubic-hy300pro-plus',
    sku: 'ZB-HY300-PRO-PLUS',
    productType: 'custom_product',
    brand: 'Magcubic',
    category: 'projectors',
    description: 'Magcubic HY300Pro Plus (HY300PRO+) Enhanced Edition. Upgraded with 2GB RAM and 16GB high-speed ROM for smooth 4K decoding and lightning-fast app navigation on Android 14.0. Features 300 ANSI Lumens brightness, 180° gyro-stabilized rotating stand, ultra-quiet hydraulic cooling fan (<25dB), Dual-Band WiFi 6, and Bluetooth 5.4.',
    shortDescription: 'Enhanced 2GB+16GB Memory • 300 ANSI Lumens • Android 14 • BT 5.4 & WiFi 6 • 180° Rotation',
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 104.67,
    salePrice: 104.67,
    costPrice: 95.15,
    pricePKR: 29150,
    costPricePKR: 26500,
    profitPKR: 2650,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hy300pro',
    currency: 'USD',
    stock: 18,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HY300Pro Plus', 'Magcubic', '2GB RAM', '16GB ROM', 'Android 14', 'ZeroByte'],
    isFeatured: true,
    isTrending: true,
    rating: 4.95,
    reviewsCount: 92,
    systemRequirements: [
      'RAM / Storage: 2GB RAM + 16GB eMMC ROM',
      'OS: Android 14.0 Smart OS',
      'Brightness: 300 ANSI Lumens',
      'Acoustics: <25dB Ultra-Quiet Fan Cooling',
      'Connectivity: Dual-Band WiFi 6 & Bluetooth 5.4',
    ],
    activationGuide: 'Complete kit includes Magcubic HY300Pro+ Projector, Bluetooth Remote, Power Cord, and ZeroByte 1-Year Guarantee.',
    createdAt: '2025-02-16T10:30:00Z',
  },
  {
    id: 'prod-ht23-projector',
    name: 'HT23 Smart Cinema Projector',
    slug: 'ht23-smart-projector',
    sku: 'ZB-HT23-PROJ',
    productType: 'custom_product',
    brand: 'Smartberry',
    category: 'projectors',
    description: 'Smartberry HT23 Smart Home Theater Projector. Features motorized electronic remote focus, Android 11.0 OS with preloaded Netflix, Prime Video, and YouTube. Supports 4K Ultra HD video playback with 260-650 ANSI lumens dynamic brightness, 5G dual-band WiFi for ultra-low latency screen mirroring, Bluetooth 5.0, and 40 to 150-inch cinematic projection.',
    shortDescription: 'Motorized Remote Focus • Pre-installed Netflix & YouTube • 5G WiFi • 4K HDR Playback',
    images: [
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 104.67,
    salePrice: 104.67,
    costPrice: 95.15,
    pricePKR: 29150,
    costPricePKR: 26500,
    profitPKR: 2650,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/ht23',
    currency: 'USD',
    stock: 22,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HT23', 'Smartberry', 'Smart Cinema', 'Motorized Focus', '5G WiFi', 'ZeroByte'],
    isFeatured: true,
    rating: 4.91,
    reviewsCount: 58,
    systemRequirements: [
      'Focus Mechanism: Electric Motorized Remote Focus',
      'Apps Preloaded: Netflix, YouTube, Prime Video, Miracast',
      'Brightness: 260-650 ANSI Lumens',
      'Screen Size: 40 - 150 Inches',
      'Ports: HDMI, USB 2.0, 3.5mm Audio Out',
    ],
    activationGuide: 'Box contains Smartberry HT23 Projector, Smart Remote, Power Adapter, and ZeroByte Verification Seal.',
    createdAt: '2025-02-16T10:45:00Z',
  },
  {
    id: 'prod-hcs350-pro',
    name: 'HCS350PRO Full HD Smart Projector',
    slug: 'hcs350pro-smart-projector',
    sku: 'ZB-HCS350-PRO',
    productType: 'custom_product',
    brand: 'HCS Optical',
    category: 'projectors',
    description: 'HCS350PRO Flagship Native 1080P Full HD Smart Projector. Delivers true 1920x1080 physical resolution with 4K decoding support, high-output 450 ANSI Lumens, and 10,000:1 dynamic contrast. Equipped with Quad-Core Cortex-A53 processor, Dual-Band WiFi 6 (2.4G & 5G), Bluetooth 5.4, 180° rotatable projection mount, automatic 4-point keystone correction, and up to 200-inch massive display screen.',
    shortDescription: 'Native 1080P Full HD • 450 ANSI Lumens • 4K Decoding • WiFi 6 & BT 5.4 • 200" Screen',
    images: [
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 136.27,
    salePrice: 136.27,
    costPrice: 123.88,
    pricePKR: 37950,
    costPricePKR: 34500,
    profitPKR: 3450,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hcs350-pro',
    currency: 'USD',
    stock: 16,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HCS350PRO', 'Native 1080P', '450 ANSI', 'WiFi 6', '4K Support', 'ZeroByte'],
    isFeatured: true,
    isTrending: true,
    rating: 4.96,
    reviewsCount: 114,
    systemRequirements: [
      'Physical Resolution: Native 1920x1080P Full HD (4K decode)',
      'Brightness: 450 ANSI Lumens',
      'Contrast Ratio: 10,000:1 Dynamic',
      'Lamp Life: 30,000 Hours LED Light Source',
      'Projection Size: 30 to 200 Inches',
    ],
    activationGuide: 'Includes HCS350PRO 1080P Projector unit, Remote, HDMI Cable, Power Cable, and Warranty Certificate.',
    createdAt: '2025-02-16T11:00:00Z',
  },
  {
    id: 'prod-hm103-a',
    name: 'HM103-A Amlogic 1080P Smart Projector',
    slug: 'hm103-a-smart-projector',
    sku: 'ZB-HM103-A',
    productType: 'custom_product',
    brand: 'Xnano / Amlogic',
    category: 'projectors',
    description: 'HM103-A High-End Smart Cinema Projector. Driven by the powerful Amlogic T950S quad-core processor with 2GB RAM and 16GB eMMC storage running Android 13.0. Features Native 1080P Full HD (1920x1080) with 4K UHD decoding, 500 ANSI Lumens brightness, full automatic optical focus, 4-point auto keystone correction, precision 270° silent metal hinge stand, Dual-Band WiFi 6, and Bluetooth 5.0.',
    shortDescription: 'Amlogic T950S • Android 13 • 2GB+16GB • 500 ANSI • Native 1080P • 270° Metal Hinge',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 154.04,
    salePrice: 154.04,
    costPrice: 140.04,
    pricePKR: 42900,
    costPricePKR: 39000,
    profitPKR: 3900,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hm103-a',
    currency: 'USD',
    stock: 12,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HM103-A', 'Amlogic T950S', 'Android 13', '500 ANSI', 'Auto Focus', 'ZeroByte'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.98,
    reviewsCount: 78,
    systemRequirements: [
      'Chipset: Amlogic T950S Quad-Core Flagship Processor',
      'RAM / ROM: 2GB DDR4 + 16GB eMMC High-Speed',
      'Brightness: 500 ANSI Lumens (Full HD 1080P Native)',
      'Hinge: 270° Heavy-Duty Silent Metal Hinge',
      'Focus & Keystone: Full Automatic Optical Focus + 4-Point Auto Keystone',
    ],
    activationGuide: 'Retail package includes HM103-A Amlogic Projector, Voice Remote, Power Cable, and Official 1-Year ZeroByte Warranty.',
    createdAt: '2025-02-16T11:15:00Z',
  },
  {
    id: 'prod-hy7-battery',
    name: 'HY7 Built-in Battery Portable Projector',
    slug: 'hy7-builtin-battery-projector',
    sku: 'ZB-HY7-BATT',
    productType: 'custom_product',
    brand: 'HY Series',
    category: 'projectors',
    description: 'HY7 Cordless Smart Projector with Built-in 5200mAh/6300mAh Rechargeable Lithium Battery for 3-4 hours of continuous wire-free outdoor camping or cinema playback. Features Native 720P with 4K decoding, 400 ANSI Lumens, multilayer double-coated F65 optical glass lens, automatic keystone correction, 30 to 300-inch massive throw range, Dual-Band WiFi 6, Bluetooth, and Type-C power input.',
    shortDescription: 'Built-in Battery (3-4h Playback) • 400 ANSI • F65 Optical Lens • 300" Max Screen • WiFi 6',
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 175.76,
    salePrice: 175.76,
    costPrice: 159.78,
    pricePKR: 48950,
    costPricePKR: 44500,
    profitPKR: 4450,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hy7-battery',
    currency: 'USD',
    stock: 14,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HY7 Battery', 'Built-in Battery', 'Cordless', '400 ANSI', 'Outdoor Cinema', 'ZeroByte'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.97,
    reviewsCount: 95,
    systemRequirements: [
      'Battery Capacity: 5200mAh/6300mAh Lithium (3-4 Hours Playback)',
      'Brightness: 400 ANSI Lumens',
      'Lens: Multilayer Double-Coated F65 Optical Glass',
      'Screen Size: 30 - 300 Inches',
      'Charging / Input: USB Type-C Fast Charge + HDMI + USB',
      'Weight: 0.38 kg Ultra-Portable',
    ],
    activationGuide: 'Box includes HY7 Battery Projector, Type-C Fast Charger, Remote, Tripod Mount, and Warranty Slip.',
    createdAt: '2025-02-16T11:30:00Z',
  },
  {
    id: 'prod-hcs350-retro-gaming',
    name: 'HCS350-Pro Dual OS 4K Retro Game Station Projector',
    slug: 'hcs350-pro-retro-game-station',
    sku: 'ZB-HCS350-GAME',
    productType: 'custom_product',
    brand: 'HCS Optical',
    category: 'projectors',
    description: 'HCS350-Pro 2-in-1 Smart Cinema Projector & Retro Gaming Station. Includes 2x 2.4GHz Wireless Gamepad Controllers and 64GB TF Card pre-loaded with 10,000+ classic arcade and console games. Features Native 1080P Full HD with 4K hardware decoding, low-latency Game Mode, 450 ANSI Lumens, Dual WiFi 6, Bluetooth 5.4, and Android Smart TV OS.',
    shortDescription: 'Dual OS Android + Retro Gaming • 2x Wireless Controllers Included • 10,000+ Games • 450 ANSI',
    images: [
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 136.27,
    salePrice: 136.27,
    costPrice: 123.88,
    pricePKR: 37950,
    costPricePKR: 34500,
    profitPKR: 3450,
    profitMarginPercent: 10,
    sourceUrl: 'https://www.zerobyte.store/products/hcs350-pro',
    currency: 'USD',
    stock: 20,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['HCS350 Gaming', 'Retro Gaming', '2 Controllers', '10000 Games', 'Native 1080P', 'ZeroByte'],
    isFeatured: true,
    rating: 4.94,
    reviewsCount: 130,
    systemRequirements: [
      'Gaming Engine: Dual Boot Android TV + Emuelec Retro Station',
      'Included: 2x 2.4GHz Wireless Controllers + 64GB Game Card (10,000+ Titles)',
      'Resolution: Native 1080P Full HD (4K Decoded)',
      'Brightness: 450 ANSI Lumens',
      'Mode: Low-Latency Instant Game Response Mode',
    ],
    activationGuide: 'Complete package: HCS350-Pro Projector, 2x Wireless Gamepads, USB Receiver, 64GB Game Card, Remote, HDMI, and Power Adapter.',
    createdAt: '2025-02-16T11:45:00Z',
  },
  {
    id: 'prod-cyberpunk',
    name: 'Cyberpunk 2077: Phantom Liberty Bundle',
    slug: 'cyberpunk-2077-phantom-liberty',
    sku: 'GM-CYBER-01',
    productType: 'gaming_product',
    brand: 'CD PROJEKT RED',
    category: 'games',
    description: 'Experience Night City with the full Cyberpunk 2077 game plus the massive Phantom Liberty spy-thriller expansion. Instant Steam Global digital activation key with lifetime ownership.',
    shortDescription: 'Steam Global PC Key • Full Game + Expansion • Instant Auto Delivery',
    images: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 59.99,
    salePrice: 34.99,
    costPrice: 22.00,
    currency: 'USD',
    stock: 24,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Steam', 'RPG', 'Action', 'Open World', 'Cyberpunk'],
    isFeatured: true,
    isTrending: true,
    isFlashDeal: true,
    isBestSeller: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    rating: 4.9,
    reviewsCount: 128,
    systemRequirements: [
      'OS: Windows 10/11 64-bit',
      'Processor: Core i7-6700 or Ryzen 5 1600',
      'Memory: 12 GB RAM',
      'Graphics: GeForce GTX 1060 6GB / Radeon RX 580',
      'DirectX: Version 12',
      'Storage: 70 GB SSD space required',
    ],
    activationGuide: '1. Launch the Steam client on your PC. 2. Click "Add a Game" in the bottom-left. 3. Select "Activate a Product on Steam...". 4. Enter your unique license key delivered to your PlayBeat Vault.',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'prod-elden-ring',
    name: 'Elden Ring: Shadow of the Erdtree Deluxe Steam Key',
    slug: 'elden-ring-shadow-of-erdtree',
    sku: 'GM-ELDEN-01',
    productType: 'gaming_product',
    brand: 'FromSoftware',
    category: 'games',
    description: 'Winner of Game of the Year. Includes Elden Ring base game and the critically acclaimed Shadow of the Erdtree DLC expansion with artbook and digital soundtrack.',
    shortDescription: 'Steam Global PC Key • GOTY Edition + Expansion • Instant Activation',
    images: [
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 79.99,
    salePrice: 49.99,
    costPrice: 38.00,
    currency: 'USD',
    stock: 18,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Steam', 'Action RPG', 'Souls-like', 'Open World', 'Elden Ring'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.98,
    reviewsCount: 312,
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'prod-black-myth',
    name: 'Black Myth: Wukong Digital Deluxe Edition PC Key',
    slug: 'black-myth-wukong-deluxe',
    sku: 'GM-WUKONG-01',
    productType: 'gaming_product',
    brand: 'Game Science',
    category: 'games',
    description: 'An action RPG rooted in Chinese mythology. Play as the Destined One venturing into the vast unknown with deluxe weapons, bronze folk outfit, and digital soundtrack.',
    shortDescription: 'Steam PC Key • Digital Deluxe Edition • Instant Key Release',
    images: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 69.99,
    salePrice: 44.99,
    costPrice: 32.00,
    currency: 'USD',
    stock: 35,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Steam', 'Action', 'Mythology', 'Souls-like'],
    isFeatured: true,
    isTrending: true,
    rating: 4.94,
    reviewsCount: 184,
    createdAt: '2025-01-14T10:00:00Z',
  },
  {
    id: 'prod-fc-25',
    name: 'EA Sports FC 25 Standard Edition Global Key',
    slug: 'ea-sports-fc-25-global',
    sku: 'GM-FC25-01',
    productType: 'gaming_product',
    brand: 'EA Sports',
    category: 'games',
    description: 'EA SPORTS FC 25 gives you more ways to win for the club. Team up with 5v5 Rush, a new way to play with friends in Football Ultimate Team, Clubs, and Kick-Off.',
    shortDescription: 'EA App / Steam Key • Global Edition • Instant Delivery',
    images: [
      'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 69.99,
    salePrice: 32.99,
    costPrice: 24.00,
    currency: 'USD',
    stock: 40,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['EA', 'Sports', 'Football', 'Multiplayer'],
    isTrending: true,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.75,
    reviewsCount: 95,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'prod-win11-pro',
    name: 'Windows 11 Professional Retail License (1 PC)',
    slug: 'windows-11-pro-license',
    sku: 'MS-WIN11-PRO',
    productType: 'software_license',
    brand: 'Microsoft',
    category: 'software',
    description: 'Genuine lifetime Microsoft Windows 11 Pro 64-bit activation key. Supports BitLocker drive encryption, Windows Sandbox, Remote Desktop, and full Microsoft updates directly.',
    shortDescription: 'Lifetime Retail Key • 1 PC Transferable • Instant Online Activation',
    images: [
      'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 199.99,
    salePrice: 19.99,
    costPrice: 9.50,
    currency: 'USD',
    stock: 88,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Microsoft', 'Windows', 'OS', 'Retail License', 'Security'],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    rating: 4.95,
    reviewsCount: 342,
    activationGuide: 'Go to Settings > System > Activation > Change Product Key. Enter your 25-character digital key and click Activate.',
    createdAt: '2025-01-01T12:00:00Z',
  },
  {
    id: 'prod-office-2024',
    name: 'Microsoft Office 2024 Professional Plus Lifetime (1 PC)',
    slug: 'microsoft-office-2024-pro-plus',
    sku: 'MS-OFF-2024',
    productType: 'software_license',
    brand: 'Microsoft',
    category: 'software',
    description: 'Full perpetual license for Word, Excel, PowerPoint, Outlook, Access, and Publisher 2024. No recurring monthly subscriptions.',
    shortDescription: 'Perpetual Lifetime Key • Word, Excel, PPT, Outlook • 1 PC Offline Binding',
    images: [
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 249.99,
    salePrice: 28.99,
    costPrice: 14.00,
    currency: 'USD',
    stock: 65,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Microsoft', 'Office', 'Productivity', 'Excel', 'Word'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.93,
    reviewsCount: 220,
    createdAt: '2025-01-05T10:00:00Z',
  },
  {
    id: 'prod-jetbrains-all',
    name: 'JetBrains All Products Pack 1-Year Commercial License',
    slug: 'jetbrains-all-products-pack',
    sku: 'DEV-JETBRAINS-1Y',
    productType: 'software_license',
    brand: 'JetBrains',
    category: 'software',
    description: 'Full suite access including IntelliJ IDEA Ultimate, PyCharm Pro, WebStorm, Rider, CLion, DataGrip, GoLand, and PhpStorm with latest AI Assistant integration.',
    shortDescription: 'All 15+ JetBrains IDEs • Full Version Updates • Instant Activation',
    images: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 289.00,
    salePrice: 49.00,
    costPrice: 25.00,
    currency: 'USD',
    stock: 12,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_year',
    tags: ['Developer', 'IDE', 'IntelliJ', 'Python', 'JavaScript'],
    isFeatured: true,
    rating: 4.96,
    reviewsCount: 88,
    createdAt: '2025-02-12T09:00:00Z',
  },
  {
    id: 'prod-nordvpn-2y',
    name: 'NordVPN 2-Year Ultimate Privacy & Security Suite',
    slug: 'nordvpn-2-year-ultimate',
    sku: 'SEC-NORD-2Y',
    productType: 'software_license',
    brand: 'NordVPN',
    category: 'software',
    description: 'Top tier military-grade VPN encryption, Threat Protection Pro anti-malware, 1TB encrypted cloud storage, and cross-platform password manager.',
    shortDescription: '2 Years Protection • 10 Devices Simultaneously • High Speed 10Gbps Servers',
    images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 199.00,
    salePrice: 49.99,
    costPrice: 22.00,
    currency: 'USD',
    stock: 50,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['VPN', 'Security', 'Privacy', 'NordVPN'],
    isTrending: true,
    rating: 4.91,
    reviewsCount: 167,
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'prod-chatgpt-plus',
    name: 'ChatGPT Plus & Codex AI 1-Month Private Subscription',
    slug: 'chatgpt-plus-1-month',
    sku: 'AI-GPT-1M',
    productType: 'saas',
    brand: 'OpenAI',
    category: 'ai-tools',
    description: 'Get GPT-4o, o1-reasoning, DALL-E 3 image generation, and deep browsing capabilities with lightning-fast response times during peak hours.',
    shortDescription: 'GPT-4o & Advanced Voice • DALL-E 3 • Custom GPTs • 30 Days Access',
    images: [
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 20.00,
    salePrice: 12.99,
    costPrice: 7.50,
    currency: 'USD',
    stock: 15,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['AI', 'OpenAI', 'ChatGPT', 'Chatbot', 'Productivity'],
    isFeatured: true,
    isFlashDeal: true,
    isBestSeller: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.92,
    reviewsCount: 210,
    createdAt: '2025-02-05T11:00:00Z',
  },
  {
    id: 'prod-claude-sonnet',
    name: 'Claude 3.5 Sonnet Pro 1-Month High-Capacity Workspace',
    slug: 'claude-3-5-sonnet-pro',
    sku: 'AI-CLAUDE-1M',
    productType: 'saas',
    brand: 'Anthropic',
    category: 'ai-tools',
    description: '5x higher usage limits for Claude 3.5 Sonnet and Opus, Artifacts live interactive coding preview, and 200k token context window analysis.',
    shortDescription: 'Claude 3.5 Sonnet • Artifacts Studio • 200K Context Window • 1 Month',
    images: [
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 20.00,
    salePrice: 13.50,
    costPrice: 8.00,
    currency: 'USD',
    stock: 25,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['Claude', 'Anthropic', 'AI', 'Coding', 'Chatbot'],
    isFeatured: true,
    isTrending: true,
    rating: 4.96,
    reviewsCount: 144,
    createdAt: '2025-02-06T11:00:00Z',
  },
  {
    id: 'prod-midjourney-v6',
    name: 'Midjourney v6 Pro Fast GPU Subscription (1 Month)',
    slug: 'midjourney-v6-pro-subscription',
    sku: 'AI-MIDJ-1M',
    productType: 'saas',
    brand: 'Midjourney',
    category: 'ai-tools',
    description: '30 hours of Fast GPU rendering time per month, unlimited Relaxed generations, stealth mode private prompts, and full commercial usage rights.',
    shortDescription: 'Midjourney v6 • Fast GPU 30h • Stealth Mode • Full Commercial License',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 60.00,
    salePrice: 26.99,
    costPrice: 15.00,
    currency: 'USD',
    stock: 20,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['AI Art', 'Midjourney', 'Image Generation', 'Design'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.97,
    reviewsCount: 180,
    createdAt: '2025-02-07T11:00:00Z',
  },
  {
    id: 'prod-cursor-ai',
    name: 'Cursor AI Pro 1-Year Full Developer License',
    slug: 'cursor-ai-pro-1-year',
    sku: 'AI-CURSOR-1Y',
    productType: 'saas',
    brand: 'Cursor',
    category: 'ai-tools',
    description: 'The AI-first code editor. Includes unlimited fast Claude 3.5 Sonnet / GPT-4o queries, multi-file code editing, agentic terminal command execution, and custom codebase indexing.',
    shortDescription: '1 Year Pro Access • Claude 3.5 & GPT-4o • Multi-file Composer • High-Speed Indexing',
    images: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 240.00,
    salePrice: 89.00,
    costPrice: 48.00,
    currency: 'USD',
    stock: 30,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_year',
    tags: ['Coding AI', 'Cursor', 'Developer', 'Claude', 'GPT'],
    isFeatured: true,
    isTrending: true,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    rating: 4.99,
    reviewsCount: 112,
    createdAt: '2025-02-08T11:00:00Z',
  },
  {
    id: 'prod-runway-gen3',
    name: 'Runway Gen-3 Alpha Video Creator Pro Plan (1 Month)',
    slug: 'runway-gen3-alpha-pro',
    sku: 'AI-RUNWAY-1M',
    productType: 'saas',
    brand: 'Runway',
    category: 'ai-tools',
    description: 'Generate hyper-realistic cinematic AI videos with Gen-3 Alpha, camera motion brush controllers, lip-sync animation, and 4K upscaling.',
    shortDescription: 'Cinematic Gen-3 Alpha • 2250 Monthly Credits • Motion Brush & 4K Upscale',
    images: [
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 35.00,
    salePrice: 19.99,
    costPrice: 11.00,
    currency: 'USD',
    stock: 14,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['AI Video', 'Runway', 'Gen-3', 'Cinematic', 'VFX'],
    rating: 4.88,
    reviewsCount: 65,
    createdAt: '2025-02-09T11:00:00Z',
  },
  {
    id: 'prod-spotify-family',
    name: 'Spotify Premium 6-Month Personal Slot',
    slug: 'spotify-premium-6-months',
    sku: 'STREAM-SPOT-6M',
    productType: 'streaming_service',
    brand: 'Spotify',
    category: 'subscriptions',
    description: 'Enjoy high fidelity ad-free music, offline track downloads, and unlimited skips on mobile, desktop, and smart speakers for 6 continuous months.',
    shortDescription: '6 Months Ad-Free • 320kbps HD Audio • Offline Downloads • Instant Slot',
    images: [
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 65.99,
    salePrice: 18.50,
    costPrice: 8.00,
    currency: 'USD',
    stock: 19,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '6_months',
    tags: ['Music', 'Spotify', 'Streaming', 'Audio'],
    isTrending: true,
    isBestSeller: true,
    rating: 4.85,
    reviewsCount: 74,
    createdAt: '2025-02-01T14:00:00Z',
  },
  {
    id: 'prod-netflix-4k',
    name: 'Netflix Premium 4K UHD Ultra HD 1-Month Private Profile',
    slug: 'netflix-premium-4k-uhd',
    sku: 'STREAM-NFLX-1M',
    productType: 'streaming_service',
    brand: 'Netflix',
    category: 'subscriptions',
    description: 'Watch all Netflix original series, blockbusters, and documentaries in 4K HDR Dolby Vision with personal pin-locked profile and uninterrupted streaming.',
    shortDescription: '4K Ultra HD • Dolby Atmos • Private PIN Profile • Instant Delivery',
    images: [
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 22.99,
    salePrice: 7.99,
    costPrice: 4.00,
    currency: 'USD',
    stock: 42,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_month',
    tags: ['Netflix', 'Streaming', 'Movies', '4K UHD'],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    rating: 4.89,
    reviewsCount: 290,
    createdAt: '2025-02-02T14:00:00Z',
  },
  {
    id: 'prod-youtube-premium',
    name: 'YouTube Premium 1-Year Individual Ad-Free & Music Pass',
    slug: 'youtube-premium-1-year',
    sku: 'STREAM-YT-1Y',
    productType: 'streaming_service',
    brand: 'Google',
    category: 'subscriptions',
    description: 'Ad-free playback across all YouTube videos, background playback while using other apps or screen off, offline downloads, and full YouTube Music Premium.',
    shortDescription: '12 Months Ad-Free YouTube + YouTube Music • Background Play • Instant',
    images: [
      'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 139.99,
    salePrice: 34.99,
    costPrice: 18.00,
    currency: 'USD',
    stock: 28,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: '1_year',
    tags: ['YouTube', 'Google', 'Streaming', 'Music'],
    isFeatured: true,
    rating: 4.93,
    reviewsCount: 160,
    createdAt: '2025-02-03T14:00:00Z',
  },
  {
    id: 'prod-steam-50',
    name: 'Steam Wallet $50 USD Global Gift Card',
    slug: 'steam-wallet-50-usd',
    sku: 'GC-STEAM-50',
    productType: 'gift_card',
    brand: 'Valve',
    category: 'gift-cards',
    description: 'Redeem $50 directly into your Steam Wallet balance. Buy any PC games, DLCs, in-game items, community market cosmetics, or hardware on Steam.',
    shortDescription: 'Global Wallet Code • No Expiry • 100% Verified Balance',
    images: [
      'https://images.unsplash.com/photo-1612287233207-6f8753235b2e?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 50.00,
    salePrice: 46.99,
    costPrice: 42.00,
    currency: 'USD',
    stock: 30,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Steam', 'Gift Card', 'Gaming', 'Valve'],
    isFeatured: true,
    isBestSeller: true,
    rating: 5.0,
    reviewsCount: 150,
    createdAt: '2025-02-10T15:00:00Z',
  },
  {
    id: 'prod-apple-50',
    name: 'Apple & iTunes $50 USD Gift Card (US & Global)',
    slug: 'apple-itunes-50-usd',
    sku: 'GC-APPLE-50',
    productType: 'gift_card',
    brand: 'Apple',
    category: 'gift-cards',
    description: 'Use for App Store purchases, Apple Music, iCloud+ storage, Apple Arcade, Apple TV+, and in-app microtransactions.',
    shortDescription: 'Official Apple Code • Instant Digital Delivery • All Apple Services',
    images: [
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 50.00,
    salePrice: 47.50,
    costPrice: 43.00,
    currency: 'USD',
    stock: 25,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Apple', 'App Store', 'iOS', 'Gift Card'],
    rating: 4.96,
    reviewsCount: 118,
    createdAt: '2025-02-11T15:00:00Z',
  },
  {
    id: 'prod-amazon-100',
    name: 'Amazon $100 USD eGift Card (No Expiration)',
    slug: 'amazon-100-usd-egift-card',
    sku: 'GC-AMZN-100',
    productType: 'gift_card',
    brand: 'Amazon',
    category: 'gift-cards',
    description: 'Shop millions of items on Amazon.com with instant balance top-up. Zero fees, no expiration date, and instant redemption.',
    shortDescription: 'Amazon Digital Voucher • $100 Full Balance • Instant Vault Delivery',
    images: [
      'https://images.unsplash.com/photo-1523474253246-7241ff8e7943?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 100.00,
    salePrice: 94.99,
    costPrice: 88.00,
    currency: 'USD',
    stock: 45,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Amazon', 'Shopping', 'Gift Card', 'Voucher'],
    isFeatured: true,
    rating: 4.98,
    reviewsCount: 204,
    createdAt: '2025-02-12T15:00:00Z',
  },
  {
    id: 'prod-bundle-ai-creator',
    name: 'Ultimate AI Creator Super-Bundle (ChatGPT + Midjourney + Runway)',
    slug: 'ultimate-ai-creator-super-bundle',
    sku: 'BDL-AI-CREATOR',
    productType: 'saas',
    brand: 'PlayBeat Bundles',
    category: 'bundles',
    description: 'All-in-one AI power suite. Includes 1-Month ChatGPT Plus (GPT-4o/o1), 1-Month Midjourney v6 Pro Fast GPU, and Runway Gen-3 Alpha Video Creator plan at a massive 60% combined discount.',
    shortDescription: 'ChatGPT Plus + Midjourney v6 + Runway Gen-3 • 3-in-1 Creator Suite • Save 60%',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 115.00,
    salePrice: 44.99,
    costPrice: 28.00,
    currency: 'USD',
    stock: 20,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['AI Bundle', 'ChatGPT', 'Midjourney', 'Runway', 'Bundles'],
    isFeatured: true,
    isBestSeller: true,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    rating: 5.0,
    reviewsCount: 142,
    createdAt: '2025-02-13T10:00:00Z',
  },
  {
    id: 'prod-bundle-streaming-pass',
    name: 'Complete Streaming Masterpass (Netflix 4K + Spotify + YouTube 1Y)',
    slug: 'complete-streaming-masterpass-bundle',
    sku: 'BDL-STREAM-PASS',
    productType: 'streaming_service',
    brand: 'PlayBeat Bundles',
    category: 'bundles',
    description: 'The ultimate entertainment trio: 6 Months Netflix 4K UHD, 6 Months Spotify Premium, and 1-Year YouTube Premium Ad-Free bundled together.',
    shortDescription: 'Netflix 4K + Spotify + YouTube Premium • All Platforms • Instant Pass Vault',
    images: [
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 228.00,
    salePrice: 54.99,
    costPrice: 30.00,
    currency: 'USD',
    stock: 15,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Streaming', 'Netflix', 'Spotify', 'YouTube', 'Bundles'],
    isFeatured: true,
    isTrending: true,
    rating: 4.95,
    reviewsCount: 89,
    createdAt: '2025-02-14T10:00:00Z',
  },
  {
    id: 'prod-bundle-dev-pack',
    name: 'Developer Productivity Power-Pack (JetBrains 1Y + Windows 11 Pro + Cursor AI)',
    slug: 'developer-productivity-power-pack',
    sku: 'BDL-DEV-POWER',
    productType: 'software_license',
    brand: 'PlayBeat Bundles',
    category: 'bundles',
    description: 'Everything a modern software engineer needs: 1-Year JetBrains All Products Pack, Windows 11 Pro Lifetime Retail license, and Cursor AI Pro code editor setup.',
    shortDescription: 'JetBrains All IDEs + Win 11 Pro + Cursor AI • Lifetime & 1Y Pro • Ultimate Dev Stack',
    images: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 528.00,
    salePrice: 129.99,
    costPrice: 65.00,
    currency: 'USD',
    stock: 10,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Developer', 'JetBrains', 'Windows 11', 'Cursor', 'Bundles'],
    isFeatured: true,
    rating: 4.99,
    reviewsCount: 78,
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prod-free-llm-runner',
    name: 'Local LLM Model Runner & Prompt Studio (Open Source)',
    slug: 'local-llm-model-runner-studio',
    sku: 'FREE-LLM-RUNNER',
    productType: 'saas',
    brand: 'PlayBeat Open Source',
    category: 'free-tools',
    description: 'Free browser-based offline-capable local LLM client and prompt engineering studio. Connect to Ollama, LM Studio, or HuggingFace with zero latency and 100% data privacy.',
    shortDescription: 'Free Local LLM Studio • Connect to Ollama & LM Studio • Zero Data Tracking • 100% Free',
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 0,
    salePrice: 0,
    costPrice: 0,
    currency: 'USD',
    stock: 9999,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Free Tool', 'AI', 'Open Source', 'Ollama', 'Local LLM'],
    isFeatured: true,
    rating: 5.0,
    reviewsCount: 230,
    activationGuide: 'Instant free download. Run locally in any browser or Docker container without requiring an account or credit card.',
    createdAt: '2025-02-16T10:00:00Z',
  },
  {
    id: 'prod-free-key-vault-gen',
    name: 'PlayBeat 256-Bit Cryptographic Vault & Password Generator',
    slug: 'cryptographic-key-vault-generator',
    sku: 'FREE-KEY-VAULT',
    productType: 'software_license',
    brand: 'PlayBeat Tools',
    category: 'free-tools',
    description: 'Generate quantum-resistant 256-bit entropy keys, password phrases, API authentication tokens, and formatted software license validation masks directly in your browser.',
    shortDescription: 'Free 256-Bit Key Generator • Quantum Entropy • Air-Gapped Safe • Instant Tool',
    images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 0,
    salePrice: 0,
    costPrice: 0,
    currency: 'USD',
    stock: 9999,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Free Tool', 'Cryptography', 'Security', 'Vault', 'Key Gen'],
    isFeatured: true,
    rating: 4.95,
    reviewsCount: 175,
    createdAt: '2025-02-16T11:00:00Z',
  },
  {
    id: 'prod-free-seo-meta',
    name: 'AI SEO Meta & Schema JSON-LD Structured Data Builder',
    slug: 'ai-seo-meta-schema-builder',
    sku: 'FREE-SEO-BUILDER',
    productType: 'saas',
    brand: 'PlayBeat Tools',
    category: 'free-tools',
    description: 'Instant free generator for OpenGraph social cards, Twitter meta tags, Product Schema JSON-LD, BreadcrumbList, and FAQPage rich snippets for Google search.',
    shortDescription: 'Free Schema Builder • Google Rich Snippets • OpenGraph & Twitter Cards • Instant',
    images: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 0,
    salePrice: 0,
    costPrice: 0,
    currency: 'USD',
    stock: 9999,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    tags: ['Free Tool', 'SEO', 'Schema', 'JSON-LD', 'Meta Tags'],
    rating: 4.91,
    reviewsCount: 140,
    createdAt: '2025-02-16T12:00:00Z',
  },
  {
    id: 'prod-fuselab-saas-kit',
    name: 'FuseLab SaaS UI/UX Enterprise Design System & Component Suite',
    slug: 'fuselab-saas-ui-ux-design-system',
    sku: 'FUSE-SAAS-UX01',
    productType: 'saas',
    brand: 'FuseLab Creative',
    category: 'software',
    description: 'Directly inspired by FuseLab Creative’s elite SaaS UI/UX architecture. Includes 280+ enterprise dashboard components, multi-tenant role-based access controllers, high-density data grids, micro-interactions, dark/light theme tokens, and production-ready React/Tailwind & Figma library.',
    shortDescription: 'Enterprise SaaS UI/UX Kit • 280+ Components • Multi-Tenant Dashboards • Figma + React',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 349.00,
    salePrice: 129.00,
    costPrice: 45.00,
    currency: 'USD',
    stock: 35,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: 'lifetime',
    tags: ['SaaS', 'UI/UX Design', 'FuseLab', 'Design System', 'Enterprise'],
    isFeatured: true,
    isTrending: true,
    rating: 4.98,
    reviewsCount: 64,
    activationGuide: 'Your digital vault will contain your private GitHub repository invitation token and Figma Enterprise library authorization key.',
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prod-respiratory-medical-ui',
    name: 'Respiratory Telemetry & Medical SaaS UI/UX Dashboard Suite',
    slug: 'respiratory-medical-saas-dashboard-suite',
    sku: 'MED-RESP-UX02',
    productType: 'saas',
    brand: 'FuseLab HealthTech',
    category: 'software',
    description: 'Clinical-grade respiratory telemetry and pulmonary diagnostics SaaS interface suite. Features real-time inductive plethysmography waveform visualizers, SpO2 & tidal volume analytics, ICU alarm prioritization grids, and HL7/FHIR compliant medical dashboard templates.',
    shortDescription: 'Respiratory Telemetry UI • Real-Time Plethysmography • HL7/FHIR Medical Dashboards',
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 499.00,
    salePrice: 179.00,
    costPrice: 60.00,
    currency: 'USD',
    stock: 22,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: 'lifetime',
    tags: ['Healthcare', 'Respiratory', 'Medical UI', 'Telemetry', 'SaaS'],
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    rating: 4.97,
    reviewsCount: 42,
    activationGuide: 'Access your download bundle and medical-grade UI token directly in your PlayBeat Digital Keys Vault.',
    createdAt: '2025-02-15T11:00:00Z',
  },
  {
    id: 'prod-pin-projector-interface',
    name: 'PIN Projector & 3D Optics Spatial UI/UX Calibration Engine',
    slug: 'pin-projector-spatial-ui-ux-engine',
    sku: 'OPT-PIN-PROJ03',
    productType: 'saas',
    brand: 'FuseLab Optix',
    category: 'software',
    description: 'High-precision spatial UI/UX system for PIN projectors, micro-laser displays, and interactive projection mapping. Includes keystone geometric correction shaders, dynamic beam alignment algorithms, multi-layer depth HUDs, and real-time gestural tracking controllers.',
    shortDescription: 'PIN Projector UI/UX • 3D Spatial Calibration • Geometric Laser Mapping SDK',
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 399.00,
    salePrice: 149.00,
    costPrice: 50.00,
    currency: 'USD',
    stock: 18,
    stockStatus: 'in_stock',
    deliveryMethod: 'instant_key',
    subscriptionDuration: 'lifetime',
    tags: ['PIN Projector', 'Optics', 'Spatial UI', 'Laser Mapping', 'SaaS'],
    isFeatured: true,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    rating: 4.95,
    reviewsCount: 38,
    activationGuide: 'Your SDK license key and 3D calibration runtime installer will be instantly unlocked in your account.',
    createdAt: '2025-02-15T12:00:00Z',
  },
  {
    id: 'prod-fuselab-sprint-service',
    name: 'FuseLab Enterprise SaaS UI/UX Audit & Design Sprint (Service)',
    slug: 'fuselab-saas-ui-ux-design-sprint',
    sku: 'SRV-FUSE-SPRINT',
    productType: 'digital_service',
    brand: 'FuseLab Creative',
    category: 'services',
    description: 'Direct 5-day bespoke enterprise SaaS UI/UX audit and prototype sprint. Covers information architecture redesign, user journey bottlenecks, conversion optimization, and custom design token system delivery by senior UX strategists.',
    shortDescription: '5-Day UI/UX Sprint • Enterprise SaaS Audit • Journey Redesign • Senior UX Team',
    images: [
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 1200.00,
    salePrice: 699.00,
    costPrice: 300.00,
    currency: 'USD',
    stock: 8,
    stockStatus: 'in_stock',
    deliveryMethod: 'manual_service',
    tags: ['UI/UX Audit', 'FuseLab', 'SaaS Consulting', 'Design Sprint'],
    isFeatured: true,
    rating: 5.0,
    reviewsCount: 19,
    activationGuide: 'After checkout, our design director will connect with your product team within 24 hours to schedule the kickoff discovery workshop.',
    createdAt: '2025-02-15T13:00:00Z',
  },
];

export const initialInventory: DigitalInventoryItem[] = [
  {
    id: 'inv-1',
    productId: 'prod-cyberpunk',
    productName: 'Cyberpunk 2077: Phantom Liberty Bundle',
    codeOrKey: 'CP77-STM-9X4K-8821-PLIB',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
    batchNumber: 'BATCH-2025-01',
  },
  {
    id: 'inv-2',
    productId: 'prod-cyberpunk',
    productName: 'Cyberpunk 2077: Phantom Liberty Bundle',
    codeOrKey: 'CP77-STM-7F2A-3390-PLIB',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
    batchNumber: 'BATCH-2025-01',
  },
  {
    id: 'inv-3',
    productId: 'prod-win11-pro',
    productName: 'Windows 11 Professional Retail License (1 PC)',
    codeOrKey: 'W11PR-VK7JG-NPHTM-C97JM-9MPGT',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
    batchNumber: 'BATCH-MS-2025',
  },
  {
    id: 'inv-4',
    productId: 'prod-win11-pro',
    productName: 'Windows 11 Professional Retail License (1 PC)',
    codeOrKey: 'W11PR-N86C9-WMX7D-28PG9-7C6B3',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
    batchNumber: 'BATCH-MS-2025',
  },
  {
    id: 'inv-5',
    productId: 'prod-win11-pro',
    productName: 'Windows 11 Professional Retail License (1 PC)',
    codeOrKey: 'W11PR-Q9BN2-7DXM9-83CKL-18YTR',
    status: 'used',
    orderId: 'ORD-98214',
    customerEmail: 'alex.gamer@example.com',
    assignedAt: '2025-02-15T12:30:00Z',
    createdAt: '2025-02-01T10:00:00Z',
    batchNumber: 'BATCH-MS-2025',
  },
  {
    id: 'inv-6',
    productId: 'prod-canva-pro',
    productName: 'Canva Pro 1-Year Educational / Team Member Access',
    codeOrKey: 'https://www.canva.com/brand/join?token=PB-CNV-8849-TEAM',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'inv-7',
    productId: 'prod-steam-50',
    productName: 'Steam Wallet $50 USD Global Gift Card',
    codeOrKey: 'STMG-50USD-4899-KMX8-0021',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'inv-8',
    productId: 'prod-jetbrains-all',
    productName: 'JetBrains All Products Pack 1-Year Commercial License',
    codeOrKey: 'JB25-UNIV-99321-K827-LIC-CERT',
    status: 'available',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'inv-fuse-1',
    productId: 'prod-fuselab-saas-kit',
    productName: 'FuseLab SaaS UI/UX Enterprise Design System & Component Suite',
    codeOrKey: 'FUSE-SAAS-PRO-8891-GH-ENTERPRISE',
    status: 'available',
    createdAt: '2025-02-15T10:00:00Z',
    batchNumber: 'BATCH-FUSE-2025',
  },
  {
    id: 'inv-fuse-2',
    productId: 'prod-fuselab-saas-kit',
    productName: 'FuseLab SaaS UI/UX Enterprise Design System & Component Suite',
    codeOrKey: 'FUSE-SAAS-PRO-4412-FIGMA-SEAT',
    status: 'available',
    createdAt: '2025-02-15T10:00:00Z',
    batchNumber: 'BATCH-FUSE-2025',
  },
  {
    id: 'inv-resp-1',
    productId: 'prod-respiratory-medical-ui',
    productName: 'Respiratory Telemetry & Medical SaaS UI/UX Dashboard Suite',
    codeOrKey: 'RESP-MED-FHIR-9901-ICU-WAVE',
    status: 'available',
    createdAt: '2025-02-15T11:00:00Z',
    batchNumber: 'BATCH-RESP-2025',
  },
  {
    id: 'inv-resp-2',
    productId: 'prod-respiratory-medical-ui',
    productName: 'Respiratory Telemetry & Medical SaaS UI/UX Dashboard Suite',
    codeOrKey: 'RESP-MED-FHIR-3382-PULM-CORE',
    status: 'available',
    createdAt: '2025-02-15T11:00:00Z',
    batchNumber: 'BATCH-RESP-2025',
  },
  {
    id: 'inv-pin-1',
    productId: 'prod-pin-projector-interface',
    productName: 'PIN Projector & 3D Optics Spatial UI/UX Calibration Engine',
    codeOrKey: 'OPTIX-PIN-PROJ-7719-3DCALIB',
    status: 'available',
    createdAt: '2025-02-15T12:00:00Z',
    batchNumber: 'BATCH-PIN-2025',
  },
  {
    id: 'inv-pin-2',
    productId: 'prod-pin-projector-interface',
    productName: 'PIN Projector & 3D Optics Spatial UI/UX Calibration Engine',
    codeOrKey: 'OPTIX-PIN-PROJ-5520-LASERMAP',
    status: 'available',
    createdAt: '2025-02-15T12:00:00Z',
    batchNumber: 'BATCH-PIN-2025',
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'PLAYBEAT10',
    description: '10% off your entire digital shopping cart',
    discountType: 'percentage',
    discountValue: 10,
    minSpend: 20,
    maxDiscount: 50,
    startsAt: '2025-01-01T00:00:00Z',
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 1000,
    usageCount: 142,
    perCustomerLimit: 3,
    isActive: true,
  },
  {
    id: 'coup-2',
    code: 'DIGITAL25',
    description: '$25 instant credit on orders over $100',
    discountType: 'fixed',
    discountValue: 25,
    minSpend: 100,
    startsAt: '2025-01-01T00:00:00Z',
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    usageCount: 88,
    perCustomerLimit: 1,
    isActive: true,
  },
  {
    id: 'coup-3',
    code: 'WELCOME5',
    description: '$5 off for new customers',
    discountType: 'fixed',
    discountValue: 5,
    minSpend: 15,
    startsAt: '2025-01-01T00:00:00Z',
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 2000,
    usageCount: 320,
    perCustomerLimit: 1,
    isActive: true,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'PB-2025-98214',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.gamer@example.com',
    customerPhone: '+1 (555) 234-5678',
    items: [
      {
        productId: 'prod-win11-pro',
        productName: 'Windows 11 Professional Retail License (1 PC)',
        productSlug: 'windows-11-pro-license',
        productImage: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80',
        productType: 'software_license',
        quantity: 1,
        unitPrice: 19.99,
        totalPrice: 19.99,
        deliveredKeys: ['W11PR-Q9BN2-7DXM9-83CKL-18YTR'],
      },
    ],
    subtotal: 19.99,
    discount: 0,
    tax: 0,
    total: 19.99,
    currency: 'USD',
    paymentMethod: 'stripe',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    orderStatus: 'completed',
    digitalDeliveries: [
      {
        id: 'deliv-1',
        productId: 'prod-win11-pro',
        productName: 'Windows 11 Professional Retail License (1 PC)',
        type: 'software_license',
        licenseKey: 'W11PR-Q9BN2-7DXM9-83CKL-18YTR',
        instructions: 'Open Windows Settings > Activation > Change Product Key to enter your genuine retail license.',
        deliveredAt: '2025-02-15T12:30:00Z',
      },
    ],
    invoiceNumber: 'INV-2025-0089',
    createdAt: '2025-02-15T12:29:40Z',
    updatedAt: '2025-02-15T12:30:00Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'PB-2025-98215',
    customerId: 'user-cust-2',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.design@example.com',
    customerPhone: '+1 (555) 789-0123',
    items: [
      {
        productId: 'prod-canva-pro',
        productName: 'Canva Pro 1-Year Educational / Team Member Access',
        productSlug: 'canva-pro-1-year',
        productImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        productType: 'subscription',
        quantity: 1,
        unitPrice: 24.99,
        totalPrice: 24.99,
        deliveredKeys: ['https://www.canva.com/brand/join?token=PB-CNV-8849-TEAM'],
      },
    ],
    subtotal: 24.99,
    discount: 2.50,
    couponCode: 'PLAYBEAT10',
    tax: 0,
    total: 22.49,
    currency: 'USD',
    paymentMethod: 'easypaisa',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    orderStatus: 'completed',
    digitalDeliveries: [
      {
        id: 'deliv-2',
        productId: 'prod-canva-pro',
        productName: 'Canva Pro 1-Year Educational / Team Member Access',
        type: 'subscription',
        downloadUrl: 'https://www.canva.com/brand/join?token=PB-CNV-8849-TEAM',
        instructions: 'Click the team invite link to join the Canva Pro workspace instantly.',
        deliveredAt: '2025-02-16T09:15:00Z',
      },
    ],
    invoiceNumber: 'INV-2025-0090',
    createdAt: '2025-02-16T09:14:10Z',
    updatedAt: '2025-02-16T09:15:00Z',
  },
];

export const initialSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    subscriptionNumber: 'SUB-PB-8812',
    customerId: 'user-cust-2',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.design@example.com',
    productId: 'prod-canva-pro',
    productName: 'Canva Pro 1-Year Educational / Team Member Access',
    planDuration: '1 Year',
    price: 24.99,
    status: 'active',
    startDate: '2025-02-16T09:15:00Z',
    expiresDate: '2026-02-16T09:15:00Z',
    autoRenew: true,
    lastBilledDate: '2025-02-16T09:14:10Z',
  },
  {
    id: 'sub-2',
    subscriptionNumber: 'SUB-PB-8813',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.gamer@example.com',
    productId: 'prod-spotify-family',
    productName: 'Spotify Premium 6-Month Personal Slot',
    planDuration: '6 Months',
    price: 18.50,
    status: 'active',
    startDate: '2025-01-10T10:00:00Z',
    expiresDate: '2025-07-10T10:00:00Z',
    autoRenew: false,
    lastBilledDate: '2025-01-10T10:00:00Z',
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-win11-pro',
    productName: 'Windows 11 Professional Retail License (1 PC)',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    title: 'Activated within 5 seconds!',
    comment: 'I was hesitant at first due to the low price, but the retail key activated directly in Windows Settings with zero hassle. Excellent instant delivery from PlayBeat Digital.',
    isVerifiedPurchase: true,
    status: 'approved',
    adminReply: 'Thank you Alex! We take pride in delivering genuine licenses instantly.',
    createdAt: '2025-02-15T13:00:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-canva-pro',
    productName: 'Canva Pro 1-Year Educational / Team Member Access',
    customerId: 'user-cust-2',
    customerName: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    title: 'Flawless Canva Pro Access',
    comment: 'Instant invite link in my digital keys vault. All premium templates, transparent PNGs and brand kits are working properly.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2025-02-16T10:00:00Z',
  },
];

export const initialTickets: Ticket[] = [
  {
    id: 'tkt-1',
    ticketNumber: 'TKT-8910',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.gamer@example.com',
    subject: 'Question regarding Steam Region compatibility',
    category: 'general',
    priority: 'medium',
    status: 'resolved',
    assignedTo: 'support_agent',
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-cust-1',
        senderName: 'Alex Rivera',
        senderRole: 'customer',
        message: 'Hi, are all Steam keys listed on PlayBeat Global or region-locked to North America?',
        createdAt: '2025-02-14T08:00:00Z',
      },
      {
        id: 'msg-2',
        senderId: 'staff-1',
        senderName: 'PlayBeat Support Team',
        senderRole: 'support',
        message: 'Hello Alex! All our game keys are 100% Global keys unless explicitly noted with a region tag (e.g. EU / NA). The Cyberpunk bundle is fully Global.',
        createdAt: '2025-02-14T08:15:00Z',
      },
    ],
    createdAt: '2025-02-14T08:00:00Z',
    updatedAt: '2025-02-14T08:15:00Z',
  },
];

export const initialBlogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'How Digital Key Licensing Works & Why OEM vs Retail Matters',
    slug: 'how-digital-key-licensing-works',
    excerpt: 'Understanding the technical differences between Retail, Volume KMS, and OEM software licenses before purchasing online.',
    content: `When purchasing digital software keys, buyers encounter two primary types of licenses: OEM (Original Equipment Manufacturer) and Retail.\n\n### 1. Retail Licenses\nRetail licenses are full standalone consumer licenses. They are tied to your personal account or machine, but critically, they can be migrated and transferred when you build or upgrade to a new PC.\n\n### 2. Digital Key Vault Security\nAt PlayBeat Digital, our server-side encryption delivers untouched vendor keys directly into your encrypted customer vault within seconds of automated payment verification.`,
    category: 'Software & Security',
    author: 'PlayBeat Tech Team',
    readTime: '4 min read',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Security', 'Windows', 'Licensing', 'Tech Guide'],
    publishedAt: '2025-02-01T12:00:00Z',
    isPublished: true,
  },
  {
    id: 'blog-2',
    title: 'Top 10 Productivity & AI Tools Every Creator Needs in 2025',
    slug: 'top-productivity-ai-tools-2025',
    excerpt: 'From LLM-powered coding assistants to Canva Pro automated rendering, optimize your creative workflow with these essential tools.',
    content: `Modern digital creators rely on modular SaaS software suites. Tools like ChatGPT Plus, Canva Pro, and JetBrains IDE packs allow single creators to perform at the scale of an entire digital agency.\n\nLearn how to bundle and manage your digital subscriptions effectively on PlayBeat Digital.`,
    category: 'Productivity & AI',
    author: 'Elena Vance',
    readTime: '6 min read',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    tags: ['AI', 'Canva', 'Creativity', 'SaaS'],
    publishedAt: '2025-02-08T09:00:00Z',
    isPublished: true,
  },
];

export const initialCMSPages: CMSPage[] = [
  {
    id: 'cms-about',
    slug: 'about',
    title: 'About PlayBeat Digital',
    metaTitle: 'About Us | PlayBeat Digital Marketplace',
    metaDescription: 'Discover the premier global destination for genuine software licenses, gaming keys, digital subscriptions, and online services.',
    content: `### Welcome to PlayBeat Digital\n\nPlayBeat Digital is a cutting-edge online marketplace engineered for instant, secure delivery of premium digital products. We connect thousands of customers worldwide to verified game keys, cloud software licenses, gift cards, and specialized digital services.\n\n#### Why Millions Trust Us\n* **Zero Waiting Time**: Instant server-side automated delivery to your secure digital vault.\n* **100% Genuine Guarantee**: Direct wholesale partnerships ensuring verified authenticity.\n* **24/7 Human Support**: Dedicated helpdesk with rapid response times.\n* **Global & Local Payments**: Supporting Stripe, JazzCash, Easypaisa, Crypto USDT, and Bank wire transfers.`,
    updatedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'cms-terms',
    slug: 'terms',
    title: 'Terms of Service',
    metaTitle: 'Terms of Service | PlayBeat Digital',
    metaDescription: 'Read our platform policies, purchasing terms, warranty terms, and account usage rules.',
    content: `### Terms of Service\n\nBy accessing PlayBeat.digital or purchasing any digital license keys, subscriptions, or services, you agree to comply with our terms.\n\n1. **Digital Deliveries**: Digital keys and activation vouchers are considered consumed upon key revelation in the customer portal.\n2. **Fair Usage**: Reselling keys obtained through promotional coupon exploitation is strictly prohibited.\n3. **Account Security**: Users are responsible for safeguarding their login credentials.`,
    updatedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'cms-refund',
    slug: 'refund-policy',
    title: 'Refund & Warranty Policy',
    metaTitle: 'Refund Policy | PlayBeat Digital',
    metaDescription: 'Transparent 7-day money-back guarantee for unredeemed or defective digital license keys.',
    content: `### 100% Activation Guarantee & Refund Policy\n\nWe offer a full replacement or refund on any digital license key that fails to activate, backed by our 7-day warranty.\n\n* **Unredeemed Keys**: Eligible for 100% refund if the key has not been unmasked or accessed.\n* **Defective Keys**: In the rare event of a vendor error, our support team will inspect and replace your key within 2 hours or issue an immediate refund.`,
    updatedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'cms-privacy',
    slug: 'privacy',
    title: 'Privacy & Security Policy',
    metaTitle: 'Privacy Policy | PlayBeat Digital',
    metaDescription: 'How we protect your personal information, order history, and payment details.',
    content: `### Privacy & Data Protection\n\nWe adhere to stringent data protection standards:\n* We never store sensitive credit card or payment PIN numbers on our servers.\n* All customer transactions and digital keys are protected with AES-256 encryption at rest.\n* We never sell customer emails or telemetry data to third parties.`,
    updatedAt: '2025-02-01T00:00:00Z',
  },
];

export const initialSettings: StoreSettings = {
  general: {
    storeName: 'PlayBeat Digital',
    tagline: 'Instant Digital Products, Gaming Keys & SaaS Subscriptions',
    supportEmail: 'support@playbeat.digital',
    supportPhone: '+1 (800) 555-BEAT',
    address: '100 Digital Harbor Way, Suite 400, San Francisco, CA',
    currency: 'USD',
    currencySymbol: '$',
    timezone: 'UTC-5 (EST)',
    maintenanceMode: false,
  },
  payments: {
    stripeEnabled: true,
    jazzcashEnabled: true,
    easypaisaEnabled: true,
    cryptoEnabled: true,
    bankTransferEnabled: true,
    testMode: true,
  },
  digitalDelivery: {
    autoDeliverOnPayment: true,
    duplicateDeliveryProtection: true,
    maskLicenseKeysInAdmin: true,
    maxDownloadLimit: 10,
    downloadExpiryDays: 365,
  },
  appearance: {
    primaryColor: '#0ea5e9',
    accentColor: '#f97316',
    heroHeadline: 'Instant Genuine Digital Keys, Subscriptions & Software',
    heroSubheadline: 'Save up to 80% on verified Steam keys, Microsoft licenses, Canva Pro, SaaS tools, and gift cards with instant automated delivery.',
    announcementBar: {
      enabled: true,
      text: '⚡ FLASH SALE: Get 10% OFF all digital items with code PLAYBEAT10',
      linkText: 'Claim Now',
      linkUrl: '#deals',
    },
  },
};

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-admin',
    userName: 'Super Admin',
    userRole: 'super_admin',
    action: 'INVENTORY_IMPORT',
    entity: 'DigitalInventory',
    entityId: 'BATCH-2025-01',
    details: 'Imported 50 new Steam global activation keys for Cyberpunk 2077 bundle.',
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'log-2',
    userId: 'user-admin',
    userName: 'Super Admin',
    userRole: 'super_admin',
    action: 'SETTINGS_UPDATE',
    entity: 'StoreSettings',
    entityId: 'payments',
    details: 'Enabled JazzCash and Easypaisa multi-gateway payment adapters.',
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-05T14:30:00Z',
  },
  {
    id: 'log-3',
    userId: 'user-staff-1',
    userName: 'Marcus Vance',
    userRole: 'store_manager',
    action: 'PRICE_UPDATE',
    entity: 'Product',
    entityId: 'prod-win11-pro',
    details: 'Updated promotional sale price from $24.99 to $19.99.',
    ipAddress: '192.168.1.45',
    createdAt: '2025-02-10T11:20:00Z',
  },
];

export const initialStaffUsers: User[] = [
  {
    id: 'user-admin',
    name: 'Chief Admin',
    email: 'admin@playbeat.digital',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    walletBalance: 500.0,
    is2FAEnabled: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    lastLogin: '2025-02-16T17:00:00Z',
  },
  {
    id: 'user-staff-1',
    name: 'Marcus Vance',
    email: 'marcus@playbeat.digital',
    role: 'store_manager',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    walletBalance: 0,
    is2FAEnabled: true,
    status: 'active',
    createdAt: '2024-06-15T00:00:00Z',
    lastLogin: '2025-02-16T15:30:00Z',
  },
  {
    id: 'user-staff-2',
    name: 'Emily Watson',
    email: 'support@playbeat.digital',
    role: 'support_agent',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    walletBalance: 0,
    is2FAEnabled: false,
    status: 'active',
    createdAt: '2024-09-01T00:00:00Z',
    lastLogin: '2025-02-16T16:10:00Z',
  },
  {
    id: 'user-cust-1',
    name: 'Alex Rivera',
    email: 'alex.gamer@example.com',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    walletBalance: 25.0,
    is2FAEnabled: false,
    status: 'active',
    createdAt: '2025-01-10T00:00:00Z',
    lastLogin: '2025-02-16T12:00:00Z',
  },
];
